routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::post('logout',['as' => 'logout', 'uses' => "Auth\LoginController@logout"]);
Route::get('logout', function(){
	Auth::logout();
	return redirect('/');
});

//Rutas para crear un perfil de usuario
Route::resource('user','PeopleController');

Route::put('user/update', ['as' => 'user/update', 'uses' => 'PeopleController@update']);


//Rutas para crear un perfil de usuario
Route::resource('post','PostController');

Route::put('post/update', ['as' => 'post/update', 'uses' => 'PostController@update']);

Route::get('post/destroy/{id}', ['as' => 'post/destroy', 'uses' => 'PostController@destroy']);

Route::post('post/search', ['as' => 'post/search', 'uses' => 'PostController@search']);

//Ruta enviar mails
Route::post('/sendmail', function(\Illuminate\Http\Request $request, \Illuminate\Mail\Mailer $mailer){
    $mailer
        ->to($request->input('mail'))
        ->send(new \App\Mail\Welcome($request->input('title'),$request->input('content')));
    return redirect()->back();
})->name('sendmail');

resources/views/peoples/listPerson.blade.php
@extends('layouts.app')
    @section("content")
    <div id="sss">
        @include('layouts.banner')
    </div>
    @include('layouts.menu')
    <div class="container">
        <h1>Perfil</h1>
        <div class="col-md-3">
            <b>Imagen de Perfil: </b><br><img class="img-thumbnail" src="imgProfiles/{{\Auth::user()->profile_picture}}"><br>
            <center>
                <a class="btn btn-submita" href="{{ route('user.edit',['id' => \Auth::user()->id] )}}">Actualizar Perfil</a> 
            </center>
        </div>
        <div class="col-md-8">
            <p><b>Nombre de usuario: </b>{{ \Auth::user()->nick_name }}</p>
            <p><b>Correo: </b>{{ \Auth::user()->email }}</p>
            <p><b>Nombres: </b>{{ \Auth::user()->first_name }}</p>
            <p><b>Apellidos: </b>{{ \Auth::user()->last_name }}</p>
            <p><b>Fecha de Nacimiento: </b>{{ \Auth::user()->birth_date }}</p>    
        </div>
        
        @if(\Auth::user()->type_user_id == 3)
            <b>Usuarios Registrados</b>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Imagen de Perfil</th>
                            <th>Nombre de Usuario</th>
                            <th>Correo</th>
                            <th>Nombres y Apellidos</th>
                            <th>Fecha de Nacimiento</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td><img class="img-thumbnail" src="imgProfiles/{{\Auth::user()->profile_picture}}"></td>
                            <td>{{ $user->nick_name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->first_name }} {{ $user->last_name }}</td>
                            <td>{{ $user->birth_date }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif
    </div>
    @endsection

resources/views/peoples/newPerson.blade.php
@extends('layouts.app')
@section('content')
<div id="sss">
    @include('layouts.banner')
</div>
@include('layouts.menu')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-ms-offst-1">
			{!! Form::open(['route' => 'user/update', 'method' => 'put','enctype' => 'multipart/form-data']) !!}
			<div class="form-group">
				<label for="nick_name">Nombre de Usuario</label>
				<input type="text" name="nick_name" value="{{$user->nick_name}}" class="form-control" >
			</div>

			<div class="form-group">
				<label for="email">Correo</label>
				<input type="text" name="email" value="{{$user->email}}" class="form-control" >
			</div>

			<div class="form-group">
				<label for="first_name">Nombres</label>
				<input type="text" name="first_name" value="{{$user->first_name}}" class="form-control" >
			</div>
			<div class="form-group">
				<label for="last_name">Apellidos</label>
				<input type="text" name="last_name" value="{{$user->last_name}}" class="form-control" >
			</div>

            <div class="form-group{{ $errors->has('urlImg') ? ' has-error' : '' }}">
	            <label for="urlImg" class="col-md-4 control-label">Imagen de Perfil</label>
	            <div class="col-md-6">
	                <input id="urlImg" type="file" class="form-control" name="urlImg" value="{{$user->profle_picture}}" >
	            </div>
            </div>

			<div class="form-group">
				{!! Form::submit('Guardar tu perfil', ['class' => 'btn btn-submita']) !!}
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>
@endsection